// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1706638236);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1706638236);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1706638236);
user_pref("app.update.lastUpdateTime.region-update-timer", 1706638236);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1706638236);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1706638236);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{f9b48f95-bd11-44d7-a6cc-e7041a4d6964}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1706638206);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 137);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b06f3adc-937b-4e31-803c-1be43e7fecec}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "always");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20231113155436");
user_pref("browser.startup.homepage_override.mstone", "115.5.0");
user_pref("browser.startup.lastColdStartupCheck", 1706638212);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "115.5.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1706638236);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20231113155436");
user_pref("extensions.lastAppVersion", "115.5.0");
user_pref("extensions.lastPlatformVersion", "115.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"59cbbeec-6f04-4dce-8bad-f20ea68921f7\",\"pictureinpicture@mozilla.org\":\"3c08c194-d9ed-4a68-880a-5e2180053185\",\"screenshots@mozilla.org\":\"f6e196c6-858f-4cc2-9983-d28f83a0748c\",\"webcompat-reporter@mozilla.org\":\"c1307596-28a9-4378-b44d-93e5baa56215\",\"webcompat@mozilla.org\":\"6d5f1c1d-82f4-45f8-bd6c-ff341ecd26ba\",\"default-theme@mozilla.org\":\"93caf82f-e93f-4ab1-bc36-bc14d4c4f733\",\"addons-search-detection@mozilla.com\":\"4644f739-babe-49b4-b5f4-95939442e1eb\",\"google@search.mozilla.org\":\"d4a773eb-9f23-49bd-a25a-c4d2964b8c85\",\"amazondotcom@search.mozilla.org\":\"f188306b-a8f3-45ad-a496-257540f213a3\",\"wikipedia@search.mozilla.org\":\"625f1df6-889a-484e-9a72-b52a3d1bbc7b\",\"bing@search.mozilla.org\":\"06e97873-7605-4103-912a-7998787b05e8\",\"ddg@search.mozilla.org\":\"94ccc4f0-c39f-4d74-ab9b-3212967d76db\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "94531e267314de661b2205c606283fb066d781e5c11027578f2a3c3aa353437c2289544074a28101b6b6f0179f0fe6bd890a0ae2bb6e1cf9053650472576366c");
user_pref("media.gmp-gmpopenh264.lastDownload", 1706638238);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1706638236);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1706638238);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "4f5d0b1b-a92f-4b61-b4b7-5d9116798852");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1706638202);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20231113155436");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
